dist:
  - trusty
    
language: 
  - cpp

before_script: |
  sudo apt-get install -y libxrandr-dev libxcursor-dev libxinerama-dev &&
  wget https://github.com/glfw/glfw/releases/download/3.2.1/glfw-3.2.1.zip && unzip glfw-3.2.1.zip &&
  cd glfw-3.2.1 && mkdir build && cd build && cmake .. && sudo make install && cd $TRAVIS_BUILD_DIR
#before_script:
#  - sudo apt-get update
#  - sudo apt-get install -y libglfw3-dev

script:
  - CXX=/usr/bin/g++ CC=/usr/bin/gcc cmake -DCOVERAGE=1 .
  - cmake --build .
  - ./unit_tests

after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' '.*gtest.*' '.*glad.*' --output-file coverage.info # filter out system & gtest
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
